"""add verdict provenance columns

Revision ID: adc3ae2a8556
Revises: 5106d5905b68
Create Date: 2026-08-02 22:27:02.320979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc3ae2a8556'
down_revision: Union[str, Sequence[str], None] = '5106d5905b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_version', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('pipeline_version', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('fusion_method', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_column('fusion_method')
        batch_op.drop_column('pipeline_version')
        batch_op.drop_column('model_version')

    # ### end Alembic commands ###
